# Assignment 3

## Name : Saket Gatyan  Roll : 1024160028  Batch : 3P11

<img src='dataset1.png'>

In [1]:
# 1
import pandas as pd
data = {'Tid':[1,2,3,4,5,6,7,8,9,10],'Refund' :['Yes','No','No','Yes','No','No','Yes','No','No','No'],'Martial Status':['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single'],'Taxable Income':['125K','100K','70K','120K','95K','60K','220K','85K','75K','90K'],'Cheat':['No','No','No','No','Yes','No','No','Yes','No','Yes']}
d1 = pd.DataFrame(data)
print(d1)
#d1.describe()

   Tid Refund Martial Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

In [2]:
#2 From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame
print(d1)
print(d1.loc[0])
print(d1.loc[4])
print(d1.loc[7])
print(d1.loc[8])

   Tid Refund Martial Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes
Tid                    1
Refund               Yes
Martial Status    Single
Taxable Income      125K
Cheat                 No
Name: 0, dtype: object
Tid                      5
Refund                  No
Martial Status    Divorced
Taxable Income         95K
Cheat                  Yes
Name: 4, dtype: object
Tid                    8
Refund                No
Martial Status    Single
Taxable Income       85K
Cheat                Yes
Name: 7, dtype: object
Tid                     9
Refund                 No
Martial Status    Married
Taxable Income        75K
Cheat                  No
Name: 8, dtype: object

In [ ]:
#3 Navigate the DataFrame and do the following task for the table created in question 1

#(i) Select row from index 3 to 7.
print(d1.loc[3:7])
#(ii) Select row from index 4 to 8, and column 2 to 4.
print(d1.iloc[4:9,2:4])
#(iii) Select all rows with column index 1 to 3 (include index 3 during selection)
print(d1.iloc[:,0:3])

   Tid Refund Martial Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
  Martial Status Taxable Income
4       Divorced            95K
5        Married            60K
6       Divorced           220K
7         Single            85K
8        Married            75K
   Tid Refund Martial Status
0    1    Yes         Single
1    2     No        Married
2    3     No         Single
3    4    Yes        Married
4    5     No       Divorced
5    6     No        Married
6    7    Yes       Divorced
7    8     No         Single
8    9     No        Married
9   10     No         Single

In [ ]:
#4 Read a csv file and display its first five rows.  
#Note-: Download dataset from https://www.kaggle.com/datasets/uciml/iris)

d2 = pd.read_csv('Iris.csv')
d2.head(n=5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
#5  From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the result

d2.drop(index=[3],columns=['SepalWidthCm'],inplace=True)
d2.head()

   Id  SepalLengthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1            1.4           0.2  Iris-setosa
1   2            4.9            1.4           0.2  Iris-setosa
2   3            4.7            1.3           0.2  Iris-setosa
4   5            5.0            1.4           0.2  Iris-setosa
5   6            5.4            1.7           0.4  Iris-setosa

<img src='dataset2.png'>

In [ ]:
#6
data2 = {'Employee ID':[101,102,103,104,105],'Name':['Alice','Bob','Charlie','Diana','Edward'],'Department':['HR','IT','IT','Marketing','Sales'],'Age':[29,34,41,28,38],'Salary':[50000,70000,65000,55000,60000],'Years_of_Experience':[4,8,10,3,12],'Joining_Date':['2020-03-15','2017-07-19','2013-06-01','2021-02-10','2010-11-25'],'Gender':['Female','Male','Male','Female','Male'],'Bonus':[5000,7000,6000,4500,5000],'Rating':[4.5,4.0,3.8,4.7,3.5]}
pf=pd.DataFrame(data2)
pf.head()
#saving the csv file in the current directory
pf.to_csv("employee.csv")

#(a)Shape (number of rows and columns) of the DataFrame.
print("a")
print(pf.shape)
#(b)Summary of the DataFrame that includes the data types and non-null counts for each column
print("b\n")
print(pf.info())
#(c)Generate descriptive statistics
print("c\n")
print(pf.describe())
#d Display the first 5 rows and last 3 rows of the dataset. 
print("d\n")
print(pf.head())
print(pf.tail(n=3))
print("\n")
#e Calculate the following statistics from the dataset
#(i)The average salary of employees
print("average salary of all employees")
print(pf['Salary'].mean())
#(ii) The average salary of employees
print("total bonus of the employee")
print(pf['Bonus'].sum())
#(iii) The youngest employee's age
print("Youngest Employee is",pf['Age'].min(),"years old")
#iv The highest performance rating.
print("Highest Peformer had the rating of",pf['Rating'].max())

#f Sort the DataFrame by the Salary column in descending order. 
#syntax would be same for multiple values
d3=pf.sort_values(by=['Salary'],ascending=False)
print(d3)

#g Add a new column that categorizes employees based on their performance rating

#The values would be added to column based on function.
#creating a function for apply function.
print("\n")
def x(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >=4.0 and rating < 4.5:
        return 'Good for rating'
    elif rating < 4.0:
        return 'Average for rating'

d3['Performance Rating'] = d3['Rating'].apply(x)
print(d3)

#h Identify missing values in the DataFrame
missing_val = d3.isnull().sum()
print(missing_val)

#i Rename the Employee_ID column to ID
d3.rename(columns={'Employee_ID':'ID'},inplace=True)

#j Rename the Employee_ID column to ID
#(i) Have more than 5 years of experience.
exp = d3['Years_of_Experience'] > 5
print("Employees with 5 or more years of experience")
print(exp.sum()) # exp alone print columns with true or false

#(ii) Belong to the IT department.
itp = d3['Department'] =='IT'
print("Total employee in IT")
print(itp.sum())

#k Modify the dataset by adding a new column, Tax, which deducts 10% of the Salary
d3['Tax'] = 0.10*d3['Salary']
print(d3)

#l saving the updated csv file
d3.to_csv("update_employee.csv")

a
(5, 10)
b

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes
None
c

       Employee ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000
d

   Employee ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
   Employee ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5


average salary of all employees
60000.0
total bonus of the employee
27500
Youngest Employee is 28 years old
Highest Peformer had the rating of 4.7
   Employee ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5


   Employee ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating  Performance Rating
1   2017-07-19    Male   7000     4.0     Good for rating
2   2013-06-01    Male   6000     3.8  Average for rating
4   2010-11-25    Male   5000     3.5  Average for rating
3   2021-02-10  Female   4500     4.7           Excellent
0   2020-03-15  Female   5000     4.5           Excellent
Employee ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance Rating     0
dtype: int64
Employees with 5 or more years of experience
3
Total employee in IT
2
   Employee ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating  Performance Rating     Tax
1   2017-07-19    Male   7000     4.0     Good for rating  7000.0
2   2013-06-01    Male   6000     3.8  Average for rating  6500.0
4   2010-11-25    Male   5000     3.5  Average for rating  6000.0
3   2021-02-10  Female   4500     4.7           Excellent  5500.0
0   2020-03-15  Female   5000     4.5           Excellent  5000.0